### ISSUE TITLE
transparency::tcp_with_no_orig_dst test fails on Mac OS

### ISSUE THREAD

**Issue by hawkw** [runconduit/conduit#226]
The proxy unit test [`transparency::tcp_with_no_orig_dest`](https://github.com/runconduit/conduit/blob/4a76c6448bff6d1ddbe044628731387fbf3368b5/proxy/tests/transparency.rs#L226-L244) fails on Macs (on the current master branch), with the following message:
```
failures:

---- tcp_with_no_orig_dst stdout ----
    thread 'tcp_with_no_orig_dst' panicked at 'assertion failed: tcp_client.try_read().is_err()', proxy/tests/transparency.rs:243:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    tcp_with_no_orig_dst

test result: FAILED. 10 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--test transparency'
```

The test appears to pass on other operating systems (or, at least, on Linux CI builds). @adleong ran the test on his Mac and also saw the error, so it doesn't appear to be specific to _my_ Mac.

I did some manual debugging with `panic!` and it seems like the value returned by `tcp_client.try_read()` is `Ok([])` rather than `Err` as expected.

**Comment by hawkw** [comment]
Here is the test output with `RUST_LOG=conduit_proxy=trace`:
```rust
     Running target/debug/deps/transparency-bd51970e61822f21

running 1 test
INFO:conduit_proxy: using controller at HostAndPort { host: Ipv4(127.0.0.1), port: 61592 }
INFO:conduit_proxy: routing on V4(127.0.0.1:61595)
INFO:conduit_proxy: proxying on V4(127.0.0.1:61594) to Some(Addr(V4(127.0.0.1:61591)))
TRACE:conduit_proxy: running
TRACE:conduit_proxy::telemetry::control: telemetry control flush_interval=Duration { secs: 10, nanos: 0 }
TRACE:conduit_proxy::control: poll rpc services
TRACE:conduit_proxy::control::discovery: poll_rpc
INFO:conduit_proxy::transport::connect: DNS resolved 127.0.0.1 to 127.0.0.1
TRACE:conduit_proxy::transport::connect: connect 127.0.0.1:61592
TRACE:conduit_proxy::control::telemetry: poll_rpc
TRACE:conduit_proxy::control::telemetry: controller unavailable
TRACE:conduit_proxy::telemetry::control: poll
TRACE:conduit_proxy::telemetry::control: recv.poll(Receiver { capacity: AtomicUsize(10000) })
TRACE:conduit_proxy::control: poll rpc services
TRACE:conduit_proxy::control::discovery: poll_rpc
TRACE:conduit_proxy::control::telemetry: poll_rpc
TRACE:conduit_proxy::telemetry::control: poll
TRACE:conduit_proxy::telemetry::control: recv.poll(Receiver { capacity: AtomicUsize(10000) })
TRACE:conduit_proxy::transparency::server: transparency did not detect protocol, treating as TCP
DEBUG:conduit_proxy::telemetry::sensor: server connection open
TRACE:conduit_proxy::telemetry::sensor: event: TransportOpen(Server(Server { proxy: Outbound(Process { node: "", scheduled_instance: "", scheduled_namespace: "" }), remote: V4(127.0.0.1:61597), local: V4(127.0.0.1:61595), orig_dst: None, protocol: Tcp }))
DEBUG:conduit_proxy::transparency::tcp: tcp accepted, no SO_ORIGINAL_DST to forward: remote=127.0.0.1:61597
TRACE:conduit_proxy::telemetry::sensor: event: TransportClose(Server(Server { proxy: Outbound(Process { node: "", scheduled_instance: "", scheduled_namespace: "" }), remote: V4(127.0.0.1:61597), local: V4(127.0.0.1:61595), orig_dst: None, protocol: Tcp }), TransportClose { clean: true, duration: Duration { secs: 0, nanos: 6794785 } })
TRACE:conduit_proxy::control: poll rpc services
TRACE:conduit_proxy::control::discovery: poll_rpc
TRACE:conduit_proxy::control::telemetry: poll_rpc
TRACE:conduit_proxy::telemetry::control: poll
TRACE:conduit_proxy::telemetry::control: recv.poll(Receiver { capacity: AtomicUsize(9998) })
TRACE:conduit_proxy::telemetry::control: recv.poll(Receiver { capacity: AtomicUsize(9999) })
TRACE:conduit_proxy::telemetry::control: recv.poll(Receiver { capacity: AtomicUsize(10000) })
test tcp_with_no_orig_dst ... FAILED

failures:

---- tcp_with_no_orig_dst stdout ----
	thread 'tcp_with_no_orig_dst' panicked at 'assertion failed: tcp_client.try_read().is_err()', proxy/tests/transparency.rs:243:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    tcp_with_no_orig_dst

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 10 filtered out
```

**Comment by olix0r** [comment]
This passes for me.

```
:; cargo test -p conduit-proxy tcp_with_no_orig_dst
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running target/debug/deps/conduit_proxy-98a66a0cf7060ada

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 13 filtered out

     Running target/debug/deps/conduit_proxy-1de45a50d4d2367e

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/discovery-ba7e768ad8991b77

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 4 filtered out

     Running target/debug/deps/telemetry-5f76b60d6c4c1239

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 3 filtered out

     Running target/debug/deps/transparency-aec191f4b66e9adc

running 1 test
test tcp_with_no_orig_dst ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 10 filtered out

   Doc-tests conduit-proxy

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

```
#; ~/b/conduit  (master ✔)
:; cargo --version
cargo 0.25.0-nightly (a88fbace4 2017-12-29)
#; ~/b/conduit  (master ✔)
:; rustc --version
rustc 1.25.0-nightly (79a521bb9 2018-01-15)
#; ~/b/conduit  (master ✔)
:; uname -a
Darwin doe.local 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64
```

**Comment by hawkw** [comment]
@olix0r interesting, I just updated to the latest Rust toolchain and the test still fails for me:
```
$ cargo test -p conduit-proxy tcp_with_no_orig_dst        
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running target/debug/deps/conduit_proxy-2dc812f740b8423b

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 13 filtered out

     Running target/debug/deps/conduit_proxy-023a6b11687bd711

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/discovery-92755e815b2ce40f

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 4 filtered out

     Running target/debug/deps/telemetry-eba31754f7094c66

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 3 filtered out

     Running target/debug/deps/transparency-b4b17c0104f1a3c0

running 1 test
test tcp_with_no_orig_dst ... FAILED

failures:

---- tcp_with_no_orig_dst stdout ----
	thread 'tcp_with_no_orig_dst' panicked at 'assertion failed: tcp_client.try_read().is_err()', proxy/tests/transparency.rs:243:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    tcp_with_no_orig_dst

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 10 filtered out
```
```
error: test failed, to rerun pass '--test transparency'
$ cargo --version                                            
cargo 0.26.0-nightly (6a8eb71f6 2018-01-13)
$ rustc --version                         
rustc 1.25.0-nightly (5965b7901 2018-01-19)
$ uname -a                                         
Darwin Elizas-MacBook-Pro.local 16.7.0 Darwin Kernel Version 16.7.0: Mon Nov 13 21:56:25 PST 2017; root:xnu-3789.72.11~1/RELEASE_X86_64 x86_64
```

**Comment by hawkw** [comment]
@franziskagoltz also reports the same failure, on the mac.
